### ISSUE TITLE
Datos de Lima (región/metropolitana) del 5 de Julio

### ISSUE THREAD

**Issue by jruizcabrejos** [jincio/COVID_19_PERU#106]
Hola!

El día 5 de julio hubo un cambio en las categorias de la variable [REGION], del Sheet3, de la base de datos reportes_minsa.xlsx

A partir de esa fecha la [REGION] LIMA paso a dividirse en LIMA METROPOLITANA y LIMA REGIÓN.

El día 4 de Julio, la [REGION] LIMA sumaba "163,824" positivos totales.
El día 5 de Julio la suma de positivos totales en LIMA METROPOLITANA y LIMA REGIÓN da "155,958".
La diferencia entre ambos días es de 7,866 positivos totales.

Quería confirmar si esta diferencia es de la fuente de los datos (los datos en "crudos"/fuente original de los datos) o si es un error de tipeo/al momento de ingresarlos al archivo excel.

Gracias!

**Comment by jincio** [comment]
Hola, Gracias por el mensaje. 
Revisando el excel me doy cuenta que la suma del 5 de Julio da 165307.  Lima metropolitana tiene 155958 y Lima región es 9349
Revisando la fuente estos coinciden con lo que está en el excel. 
La fuente la puedes encontrar en la carpeta Data donde hemos bajado los excel diarios de la sala situacional. 
Espero ayude.

**Comment by jruizcabrejos** [comment]
Mi error! Encontre que el problema estaba en la tilde y como la manejé. 

Estaba leyendo un script externo con source('_scripts/data.R', echo = TRUE). Al agregar el argumento "encoding="UTF-8" se solucionó mi problema.

De todos modos aprovecho en mencionar algo que recientemente noté:
Los datos del 29 de junio y 30 de junio son iguales en el "Sheet3" de la base de datos reportes_minsa.xlsx.
(o eso me parece).

**Comment by jincio** [comment]
Gracias por avisar lo del 29 y 30 :). Ya esta corregido!
Cerrare este issue. Cualquier otro tema que veas abres otro issue porfa.
