### ISSUE TITLE
Mejorar gráficos de tendencias

### ISSUE THREAD

**Issue by jincio** [jincio/COVID_19_PERU#14]
- Los números de los labels están muy grandes, quizás cambiarlos a como están las líneas departamentales.

**Comment by jincio** [comment]
He cambiado los labels de los gráficos. Ahora en las barras se muestran verticales y los de las líneas ya no tienen el box.

**Comment by calderonsamuel** [comment]
Recién veo esto, para mañana lo tengo

**Comment by jincio** [comment]
Creo que las series ya están mejor. Cerraré este issue
