### ISSUE TITLE
Datos a nivel de región no actualizados (?)

### ISSUE THREAD

**Issue by jruizcabrejos** [jincio/COVID_19_PERU#66]
Hola!

En el archivo reportes_minsa.xlsx, en la hoja Sheet3, los datos del día 26/05 son los mismos que el día 25/05. 

Asumo que es un error o los datos no se encontraban disponibles aún?

**Comment by jincio** [comment]
Hola, 

Gracias por avisar. Reviso ahora y te aviso.

**Comment by jincio** [comment]
Tenías razón! ya corregí la data y el site. 
Muchas gracias
