### ISSUE TITLE
Data 02/06

### ISSUE THREAD

**Issue by jarangoitia** [jincio/COVID_19_PERU#74]
El total de casos del archivo del 02/06 no coincide con el valor publicado (174,884), tampoco el número de pruebas (1,092,646)

**Comment by jincio** [comment]
Hola, 
Gracias. Ahora bien, he revisado el comunicado del MINSA de donde sacamoas la info para "reporte_minsa.xlsx" y los datos coinciden https://www.gob.pe/institucion/minsa/noticias/170945-minsa-casos-confirmados-por-coronavirus-covid-19-ascienden-a-174-884-en-el-peru-comunicado-n-119 
Ten encuenta que las PR están separadas de las PCR. 

Me avisas cualquier cosa

**Comment by jarangoitia** [comment]
Hola José

Comparé la data del archivo de la sala situacional con el repote Minsa del link y hay una  inconsistencia en el total de casos positivos de Lima, pues en el archivo de la sala situacional dice 109,078 mientras que el reporte indica 105,797. Para encontrar el origen de la inconsistencia compare el total de positivos de todo el Perú por PCR y por prueba rápida, de ambas fuentes y encontré que el número de positivos PCR coincide, mas no el de rápida pues justamente hay la inconsistencia está en Lima (81,764 según sala situacional y 78,483 según reporte MINSA). Utilizando el valor del reporte MINSA, ya todos los valores entre ambos reportes coinciden.
También hay inconsistencias en el número de muestras, pero ese es más complicado de validar pues el reporte MINSA no te da el detalle del número de muestras por región.

**Comment by jincio** [comment]
Hola, 

Gracias por chequear. Estuve revisando la data y para Lima (hoja 3 del "reportes_minsa.xlsx" tenemos 

PE | LIMA | 27314 | 81764 |   | 109078

¿Cuando te refieres al reporte que indica 105797? Te estas refiriendo a este archivo: "reportes_minsa.xlsx"? 
Si es así, me parece que ahora coinciden. En el repo también tenemos los exceles que saca la sala situacional por cada día, así que si hay un error podemos reconstruir el excel.

**Comment by jarangoitia** [comment]
Hola José

El enlace: https://www.gob.pe/institucion/minsa/noticias/170945-minsa-casos-confirmados-por-coronavirus-covid-19-ascienden-a-174-884-en-el-peru-comunicado-n-119 indica que para Lima hay 105797 casos, mientras que el Excel "reportes_minsa.xlsx" indica que hay 109078. A esa diferencia me refiero

**Comment by jincio** [comment]
Hola, 
Tienes mucha razón! El tema es que la sala situacional reporto 109078 para Lima. En el repo tenemos todas las descargas de la Sala Situacional, la del 2 de Junion está aquí https://github.com/jincio/COVID_19_PERU/blob/master/data/descargas_sala_situacional/POSITIVIDAD_02062020.xlsx
Y allí indica 109078. Es una inconsistencia entre lo reportado en la nota de prensa y lo reportado en la situacional.  No se me ocurre que hacer, pero estoy agregando una nota con tu observación en el "reporte minsa"
